language: ruby
rvm:
  - "1.8.7"
  - "1.9.3"
  - jruby-18mode
  - jruby-19mode
  - rbx-18mode
  - rbx-19mode
before_script:
  - git submodule init
  - git submodule update
  - npm install
script: bundle exec rake test